SELECT TOP (1000) [ITEMSID]
      ,[ITEMS]
      ,[STOCK]
      ,[AMOUNT]
      ,[ORDERPRICE]
      ,[ORDERID]
      ,[CLIENTNAME]
      ,[ORDERDATE]
  FROM [SalesRef].[dbo].[SalesItem]

  -- MOST WANTED ITEMS
SELECT ITEMS, COUNT(ITEMS) AS SOLD_ITEMS
FROM SalesItem
GROUP BY ITEMS
ORDER BY SOLD_ITEMS DESC;

SELECT ITEMS, COUNT(ITEMS) AS SOLD_ITEMS
FROM SalesItem
WHERE ITEMS like '%server%'
GROUP BY ITEMS
ORDER BY SOLD_ITEMS DESC;

SELECT ITEMS, COUNT(ITEMS) AS SOLD_ITEMS
FROM SalesItem
WHERE ITEMS like '%cpu%'
GROUP BY ITEMS
ORDER BY SOLD_ITEMS DESC;

SELECT ITEMS, COUNT(ITEMS) AS SOLD_ITEMS
FROM SalesItem
WHERE ITEMS like '%ram%'
GROUP BY ITEMS
ORDER BY SOLD_ITEMS DESC;

SELECT ITEMS, COUNT(ITEMS) AS SOLD_ITEMS
FROM SalesItem
WHERE ITEMS like '%ssd%'
GROUP BY ITEMS
ORDER BY SOLD_ITEMS DESC;